// AUTO-GENERATED by scripts/gen-schema-data.mjs. Do not edit by hand.
import type { SchemaItem } from "./strings";

export const SCHEMA: SchemaItem[] = [
  {
    "type": "string",
    "name": "app_name",
    "key": "s:app_name",
    "value": "PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": true
  },
  {
    "type": "string",
    "name": "website_url",
    "key": "s:website_url",
    "value": "PodLP.com",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": false
  },
  {
    "type": "string",
    "name": "podlp_logo",
    "key": "s:podlp_logo",
    "value": "PodLP Logo",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": true
  },
  {
    "type": "string",
    "name": "about_text",
    "key": "s:about_text",
    "value": "Version: %1$s (%2$s)<br /><br /><b>PodLP</b> is a podcast app designed specifically for Android phones with keypads. Podcasts are an important source of information, education, and entertainment. With PodLP, you can discover, listen, and download podcasts from around the world for free.<br /><br />Contact <u>%3$s</u> to suggest new features or report issues.",
    "cdata": true,
    "multiline": true,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "settings",
    "key": "s:settings",
    "value": "Settings",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "about",
    "key": "s:about",
    "value": "About",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "close",
    "key": "s:close",
    "value": "Close",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "select",
    "key": "s:select",
    "value": "Select",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "exit",
    "key": "s:exit",
    "value": "Exit",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "contact_podlp",
    "key": "s:contact_podlp",
    "value": "Contact PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "visit",
    "key": "s:visit",
    "value": "Visit",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "play",
    "key": "s:play",
    "value": "Play",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "pause",
    "key": "s:pause",
    "value": "Pause",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "resume",
    "key": "s:resume",
    "value": "Resume",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "podcast_thumbnail",
    "key": "s:podcast_thumbnail",
    "value": "Podcast thumbnail",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "number_of_episodes",
    "key": "s:number_of_episodes",
    "value": "Episodes (%1$d)",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "number_of_episodes_truncated",
    "key": "s:number_of_episodes_truncated",
    "value": "Episodes (%1$d+)",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "load_all_episodes",
    "key": "s:load_all_episodes",
    "value": "Load All Episodes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "network_error",
    "key": "s:network_error",
    "value": "Network error",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "error_loading_podcast",
    "key": "s:error_loading_podcast",
    "value": "Error loading podcast",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "category_not_found",
    "key": "s:category_not_found",
    "value": "Category not found",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "no_network_connection",
    "key": "s:no_network_connection",
    "value": "No network connection",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "menu",
    "key": "s:menu",
    "value": "Menu",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "today",
    "key": "s:today",
    "value": "Today",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "yesterday",
    "key": "s:yesterday",
    "value": "Yesterday",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "cancel",
    "key": "s:cancel",
    "value": "Cancel",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "app_language",
    "key": "s:app_language",
    "value": "App language",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "text_size",
    "key": "s:text_size",
    "value": "Text size",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "small",
    "key": "s:small",
    "value": "Small",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "medium",
    "key": "s:medium",
    "value": "Medium",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "large",
    "key": "s:large",
    "value": "Large",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe",
    "key": "s:subscribe",
    "value": "Subscribe",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sort",
    "key": "s:sort",
    "value": "Sort",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sort_default",
    "key": "s:sort_default",
    "value": "Default",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "sort_newest_to_oldest",
    "key": "s:sort_newest_to_oldest",
    "value": "Newest to Oldest ↓",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "sort_oldest_to_newest",
    "key": "s:sort_oldest_to_newest",
    "value": "Oldest to Newest ↑",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "season",
    "key": "s:season",
    "value": "Season",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "all_episodes",
    "key": "s:all_episodes",
    "value": "All Episodes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "season_number",
    "key": "s:season_number",
    "value": "Season %1$d",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "go_to_podcast_website",
    "key": "s:go_to_podcast_website",
    "value": "Go to Podcast Website",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "search",
    "key": "s:search",
    "value": "Search",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "search_podcasts",
    "key": "s:search_podcasts",
    "value": "Search for podcasts…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "shortcut_search_long",
    "key": "s:shortcut_search_long",
    "value": "Search for podcasts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "shortcut_settings_long",
    "key": "s:shortcut_settings_long",
    "value": "Open settings",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "shortcut_open_app",
    "key": "s:shortcut_open_app",
    "value": "Open PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "back",
    "key": "s:back",
    "value": "Back",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "unsubscribe",
    "key": "s:unsubscribe",
    "value": "Unsubscribe",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribed_to_podcast",
    "key": "s:subscribed_to_podcast",
    "value": "Subscribed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "duration",
    "key": "s:duration",
    "value": "Duration",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "publish_date",
    "key": "s:publish_date",
    "value": "Publish date",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "published",
    "key": "s:published",
    "value": "Published",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "size",
    "key": "s:size",
    "value": "Size",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "size_in_gb",
    "key": "s:size_in_gb",
    "value": "%.1fGB",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": true
  },
  {
    "type": "string",
    "name": "size_in_mb",
    "key": "s:size_in_mb",
    "value": "%dMB",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": true
  },
  {
    "type": "string",
    "name": "size_in_kb",
    "key": "s:size_in_kb",
    "value": "%dKB",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": true
  },
  {
    "type": "string",
    "name": "successfully_subscribed",
    "key": "s:successfully_subscribed",
    "value": "Successfully subscribed!",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "successfully_unsubscribed",
    "key": "s:successfully_unsubscribed",
    "value": "Successfully unsubscribed!",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "speed",
    "key": "s:speed",
    "value": "Speed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "system_default",
    "key": "s:system_default",
    "value": "System default",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "light",
    "key": "s:light",
    "value": "Light",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "dark",
    "key": "s:dark",
    "value": "Dark",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "theme",
    "key": "s:theme",
    "value": "Theme",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "now_playing",
    "key": "s:now_playing",
    "value": "Now playing",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "completed",
    "key": "s:completed",
    "value": "Completed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "mark_as_played",
    "key": "s:mark_as_played",
    "value": "Mark as played",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "mark_as_unplayed",
    "key": "s:mark_as_unplayed",
    "value": "Mark as unplayed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "categories",
    "key": "s:categories",
    "value": "Categories",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "arts",
    "key": "s:arts",
    "value": "Arts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "business",
    "key": "s:business",
    "value": "Business",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "comedy",
    "key": "s:comedy",
    "value": "Comedy",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "education",
    "key": "s:education",
    "value": "Education",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "fiction",
    "key": "s:fiction",
    "value": "Fiction",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "government",
    "key": "s:government",
    "value": "Government",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "health_and_fitness",
    "key": "s:health_and_fitness",
    "value": "Health & Fitness",
    "cdata": true,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "history",
    "key": "s:history",
    "value": "History",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "kids_and_family",
    "key": "s:kids_and_family",
    "value": "Kids & Family",
    "cdata": true,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "leisure",
    "key": "s:leisure",
    "value": "Leisure",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "music",
    "key": "s:music",
    "value": "Music",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "news",
    "key": "s:news",
    "value": "News",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "religion_and_spirituality",
    "key": "s:religion_and_spirituality",
    "value": "Religion & Spirituality",
    "cdata": true,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "science",
    "key": "s:science",
    "value": "Science",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "society_and_culture",
    "key": "s:society_and_culture",
    "value": "Society & Culture",
    "cdata": true,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sports",
    "key": "s:sports",
    "value": "Sports",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "tv_and_film",
    "key": "s:tv_and_film",
    "value": "TV & Film",
    "cdata": true,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "technology",
    "key": "s:technology",
    "value": "Technology",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "true_crime",
    "key": "s:true_crime",
    "value": "True Crime",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "api_service",
    "key": "s:api_service",
    "value": "API Service",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "apple_podcasts",
    "key": "s:apple_podcasts",
    "value": "Apple Podcasts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "podcast_index",
    "key": "s:podcast_index",
    "value": "Podcast Index",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "analytics_enabled",
    "key": "s:analytics_enabled",
    "value": "Share usage data",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "analytics_enabled_description",
    "key": "s:analytics_enabled_description",
    "value": "Help improve PodLP by sharing anonymous usage data",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "import_subscriptions",
    "key": "s:import_subscriptions",
    "value": "Import Subscriptions",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "import_subscriptions_description",
    "key": "s:import_subscriptions_description",
    "value": "Import podcasts from OPML file",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "export_subscriptions",
    "key": "s:export_subscriptions",
    "value": "Export Subscriptions",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "export_subscriptions_description",
    "key": "s:export_subscriptions_description",
    "value": "Export podcasts to OPML",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "clear_cache",
    "key": "s:clear_cache",
    "value": "Clear cache",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "clear_cache_description",
    "key": "s:clear_cache_description",
    "value": "Delete all cached images and data",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "create_contact_shortcut",
    "key": "s:create_contact_shortcut",
    "value": "Create contact",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "create_contact_shortcut_description",
    "key": "s:create_contact_shortcut_description",
    "value": "Create shortcut to launch PodLP from Contacts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "importing_podcasts",
    "key": "s:importing_podcasts",
    "value": "Importing podcasts…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "exporting_podcasts",
    "key": "s:exporting_podcasts",
    "value": "Exporting podcasts…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "import_complete_title",
    "key": "s:import_complete_title",
    "value": "Import Complete",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "import_complete",
    "key": "s:import_complete",
    "value": "%1$d of %2$d podcasts imported successfully",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "import_cancelled",
    "key": "s:import_cancelled",
    "value": "Import cancelled",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "failed_imports",
    "key": "s:failed_imports",
    "value": "Failed to import:",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "opml_no_podcasts_found",
    "key": "s:opml_no_podcasts_found",
    "value": "No podcasts found in OPML file",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "opml_import_failed",
    "key": "s:opml_import_failed",
    "value": "Import failed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "opml_no_subscriptions_to_export",
    "key": "s:opml_no_subscriptions_to_export",
    "value": "No subscriptions to export",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "opml_could_not_retrieve_feed_urls",
    "key": "s:opml_could_not_retrieve_feed_urls",
    "value": "Could not retrieve feed URLs",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "opml_export_failed",
    "key": "s:opml_export_failed",
    "value": "Export failed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "export_complete",
    "key": "s:export_complete",
    "value": "Exported %1$d podcasts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "ok",
    "key": "s:ok",
    "value": "OK",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "error",
    "key": "s:error",
    "value": "Error",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "opml_import_label",
    "key": "s:opml_import_label",
    "value": "Import OPML",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "opml_no_file_provided",
    "key": "s:opml_no_file_provided",
    "value": "No OPML file provided",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "parsing_opml",
    "key": "s:parsing_opml",
    "value": "Parsing OPML file…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe_activity_label",
    "key": "s:subscribe_activity_label",
    "value": "Subscribe to Podcast",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe_no_feed_url",
    "key": "s:subscribe_no_feed_url",
    "value": "No podcast feed URL provided",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribing_to_podcast",
    "key": "s:subscribing_to_podcast",
    "value": "Subscribing to podcast…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe_success_message",
    "key": "s:subscribe_success_message",
    "value": "Successfully subscribed to %1$s",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe_podcast_not_found",
    "key": "s:subscribe_podcast_not_found",
    "value": "Podcast not found",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "subscribe_failed",
    "key": "s:subscribe_failed",
    "value": "Failed to subscribe",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "update_available_title",
    "key": "s:update_available_title",
    "value": "Update Available",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "update_available_message",
    "key": "s:update_available_message",
    "value": "A new version of PodLP is available to install.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "update_downloaded_message",
    "key": "s:update_downloaded_message",
    "value": "A new version of PodLP has been downloaded and is ready to install.",
    "cdata": false,
    "multiline": true,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "download",
    "key": "s:download",
    "value": "Download",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "install",
    "key": "s:install",
    "value": "Install",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "permission_denied_install_updates",
    "key": "s:permission_denied_install_updates",
    "value": "Permission to install updates denied. Please enable it in settings.",
    "cdata": false,
    "multiline": true,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "podlp_update",
    "key": "s:podlp_update",
    "value": "PodLP Update",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "downloading_new_version",
    "key": "s:downloading_new_version",
    "value": "Downloading new version of PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "downloading_update",
    "key": "s:downloading_update",
    "value": "Downloading update…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "update_download_failed_reason",
    "key": "s:update_download_failed_reason",
    "value": "Update download failed: %1$d",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "download_complete_installing",
    "key": "s:download_complete_installing",
    "value": "Download complete. Installing update…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "update_installed_successfully",
    "key": "s:update_installed_successfully",
    "value": "Update installed successfully.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "check_for_updates",
    "key": "s:check_for_updates",
    "value": "Check for updates",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "up_to_date",
    "key": "s:up_to_date",
    "value": "You're up to date",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "whats_new",
    "key": "s:whats_new",
    "value": "What's New",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "changelog",
    "key": "s:changelog",
    "value": "Changelog",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "privacy_policy",
    "key": "s:privacy_policy",
    "value": "Privacy Policy",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "terms_of_service",
    "key": "s:terms_of_service",
    "value": "Terms of Service",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "invalid_date_title",
    "key": "s:invalid_date_title",
    "value": "Invalid Date",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "invalid_date_message",
    "key": "s:invalid_date_message",
    "value": "The date on your phone is <u>%1$s</u>. Please adjust the date to use PodLP.",
    "cdata": false,
    "multiline": true,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "adjust",
    "key": "s:adjust",
    "value": "Adjust",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "ad",
    "key": "s:ad",
    "value": "Ad",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string-array",
    "name": "changelog",
    "key": "a:changelog",
    "items": [
      {
        "value": "Welcome to PodLP!",
        "cdata": true
      },
      {
        "value": "<i>Fix</i> several crashes and bugs",
        "cdata": true
      },
      {
        "value": "Ability to <b>Search Episodes</b> within a podcast",
        "cdata": true
      },
      {
        "value": "<b>Show Notes</b> and Podcast Descriptions now available from the menu",
        "cdata": true
      },
      {
        "value": "Reduce streaming data use with <i>Alternate Enclosure</i> on supported podcasts",
        "cdata": true
      },
      {
        "value": "Visit <a href=\"https://podlp.com\">PodLP.com</a> for more",
        "cdata": true
      }
    ],
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "play_next",
    "key": "s:play_next",
    "value": "Play next",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "delete_episode",
    "key": "s:delete_episode",
    "value": "Delete episode",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "downloaded",
    "key": "s:downloaded",
    "value": "Downloaded",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "downloading",
    "key": "s:downloading",
    "value": "Downloading…",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "download_failed",
    "key": "s:download_failed",
    "value": "Download failed",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "could_not_download_episode",
    "key": "s:could_not_download_episode",
    "value": "Could not download %1$s",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "download_complete",
    "key": "s:download_complete",
    "value": "Download Complete",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "episode_ready_to_play",
    "key": "s:episode_ready_to_play",
    "value": "%1$s ready to play",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "episode",
    "key": "s:episode",
    "value": "Episode",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "auto_download",
    "key": "s:auto_download",
    "value": "Auto-download",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "auto_download_description",
    "key": "s:auto_download_description",
    "value": "Automatically download new episodes for subscriptions",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "episodes_to_retain",
    "key": "s:episodes_to_retain",
    "value": "Episodes to retain",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "episodes_to_retain_description",
    "key": "s:episodes_to_retain_description",
    "value": "Keep %1$s latest episodes downloaded per podcast",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "episodes_to_retain_unlimited",
    "key": "s:episodes_to_retain_unlimited",
    "value": "Keep all episodes downloaded",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "unlimited",
    "key": "s:unlimited",
    "value": "Unlimited",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "debug_delete_all_downloads",
    "key": "s:debug_delete_all_downloads",
    "value": "Delete all downloads",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "debug_trigger_auto_download",
    "key": "s:debug_trigger_auto_download",
    "value": "Trigger auto-download",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "deleted_all_downloads",
    "key": "s:deleted_all_downloads",
    "value": "Deleted all downloaded episodes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "auto_download_triggered",
    "key": "s:auto_download_triggered",
    "value": "Auto-download worker triggered",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "recommended_podcasts",
    "key": "s:recommended_podcasts",
    "value": "Recommended podcasts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "recommended",
    "key": "s:recommended",
    "value": "Recommended",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sponsored",
    "key": "s:sponsored",
    "value": "Sponsored",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "my_podcasts",
    "key": "s:my_podcasts",
    "value": "My podcasts",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "top_chart",
    "key": "s:top_chart",
    "value": "Top chart",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "browse_category",
    "key": "s:browse_category",
    "value": "Browse %1$s",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "no_recommended_podcasts",
    "key": "s:no_recommended_podcasts",
    "value": "No recommended podcasts found",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sleep_timer",
    "key": "s:sleep_timer",
    "value": "Sleep timer",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sleep_timer_off",
    "key": "s:sleep_timer_off",
    "value": "Off",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sleep_timer_end_of_episode",
    "key": "s:sleep_timer_end_of_episode",
    "value": "End of episode",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sleep_timer_minutes",
    "key": "s:sleep_timer_minutes",
    "value": "%1$d minutes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "sleep_timer_hour",
    "key": "s:sleep_timer_hour",
    "value": "1 hour",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "episode_page_artwork",
    "key": "s:episode_page_artwork",
    "value": "Episode page artwork",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "episode_artwork",
    "key": "s:episode_artwork",
    "value": "Episode artwork",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "podcast_artwork",
    "key": "s:podcast_artwork",
    "value": "Podcast artwork",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "muted",
    "key": "s:muted",
    "value": "Muted",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "funding",
    "key": "s:funding",
    "value": "Support podcast",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "options",
    "key": "s:options",
    "value": "Options",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "not_supported",
    "key": "s:not_supported",
    "value": "Not Supported",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "no_contacts_app_available",
    "key": "s:no_contacts_app_available",
    "value": "No contacts app available",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "percentage_format",
    "key": "s:percentage_format",
    "value": "%1$d%%",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": false
  },
  {
    "type": "string",
    "name": "speed_format",
    "key": "s:speed_format",
    "value": "%1$sx",
    "cdata": false,
    "multiline": false,
    "translatable": false,
    "matched": false
  },
  {
    "type": "string",
    "name": "persistent_notification",
    "key": "s:persistent_notification",
    "value": "Shortcut notification",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "persistent_notification_description",
    "key": "s:persistent_notification_description",
    "value": "Show persistent notification to open PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "launcher_notification_channel",
    "key": "s:launcher_notification_channel",
    "value": "App Launcher",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "launcher_notification_channel_description",
    "key": "s:launcher_notification_channel_description",
    "value": "Persistent notification for quick access to PodLP",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "launcher_notification_text",
    "key": "s:launcher_notification_text",
    "value": "Tap to open",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "enabled",
    "key": "s:enabled",
    "value": "Enabled",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "disabled",
    "key": "s:disabled",
    "value": "Disabled",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "storage_location",
    "key": "s:storage_location",
    "value": "Storage location",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "storage_location_description",
    "key": "s:storage_location_description",
    "value": "Where downloaded episodes are saved",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "storage_default",
    "key": "s:storage_default",
    "value": "System default",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": true
  },
  {
    "type": "string",
    "name": "storage_internal",
    "key": "s:storage_internal",
    "value": "Internal storage",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "storage_external",
    "key": "s:storage_external",
    "value": "External storage",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "auto_delete",
    "key": "s:auto_delete",
    "value": "Auto-delete",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "auto_delete_description",
    "key": "s:auto_delete_description",
    "value": "Automatically delete downloaded episodes after listening",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "show_notes",
    "key": "s:show_notes",
    "value": "Show notes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "podcast_description",
    "key": "s:podcast_description",
    "value": "Podcast description",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "search_episodes",
    "key": "s:search_episodes",
    "value": "Search Episodes",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "unknown_episode",
    "key": "s:unknown_episode",
    "value": "Unknown episode",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_network_error",
    "key": "s:playback_network_error",
    "value": "Network error. Check your connection.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_file_not_found",
    "key": "s:playback_file_not_found",
    "value": "Episode file not found. Re-download and try again.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_format_unsupported",
    "key": "s:playback_format_unsupported",
    "value": "This episode format is not supported.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_download_corrupted",
    "key": "s:playback_download_corrupted",
    "value": "Downloaded episode may be corrupted. Try re-downloading.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_stream_unavailable",
    "key": "s:playback_stream_unavailable",
    "value": "Unable to stream. Try again later.",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  },
  {
    "type": "string",
    "name": "playback_error",
    "key": "s:playback_error",
    "value": "Playback error: %1$s",
    "cdata": false,
    "multiline": false,
    "translatable": true,
    "matched": false
  }
];
